# Tells Jekyll where your actual site files are
source: client
destination: _site

# Exclude the node_modules directory from Jekyll's build process
# This also applies to any node_modules directly under the source (client folder)
exclude:
  - client/node_modules/
  - server/ # Exclude your backend entirely
  - .git/
  - .github/ # Exclude GitHub Actions workflows
